In [3]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.6.0


In [5]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11501568/11490434 [==============================] - 0s 0us/step


In [6]:
model = tf.keras.models.Sequential([
    tf. keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [7]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.34801012, -0.09819149,  0.14100038, -0.46497607, -0.37989208,
         0.38738745, -0.0389876 ,  0.18660767,  0.14678788,  0.0915949 ]],
      dtype=float32)

In [8]:
tf.nn.softmax(predictions).numpy()

array([[0.07082057, 0.09091891, 0.11548723, 0.06300307, 0.06859829,
        0.14775375, 0.0964642 , 0.12087625, 0.11615755, 0.10992017]],
      dtype=float32)

In [9]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [10]:
loss_fn(y_train[:1], predictions).numpy()

1.9122082

In [12]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [13]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2937 - accuracy: 0.9154
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1447 - accuracy: 0.9571
Epoch 3/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1055 - accuracy: 0.9687
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0885 - accuracy: 0.9726
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0750 - accuracy: 0.9765


In [15]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 0s - loss: 0.0711 - accuracy: 0.9779


[0.07111598551273346, 0.9779000282287598]

In [16]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [17]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[5.6378706e-08, 6.2096563e-09, 9.5283040e-06, 6.8559026e-04,
        2.8709080e-10, 2.9729647e-06, 2.5280120e-13, 9.9928999e-01,
        2.5258979e-08, 1.1864603e-05],
       [2.6473243e-08, 2.0107802e-05, 9.9992645e-01, 5.1235984e-05,
        4.7788307e-16, 2.3729366e-07, 1.3862861e-08, 5.8424283e-16,
        1.8944220e-06, 3.5644573e-12],
       [1.6544699e-07, 9.9939883e-01, 7.1674498e-05, 3.9278898e-06,
        7.2467274e-06, 1.2375223e-06, 1.1438308e-05, 3.2440235e-04,
        1.7863182e-04, 2.4543449e-06],
       [9.9994481e-01, 5.2975008e-10, 1.8812376e-05, 2.0808730e-07,
        3.5232054e-07, 5.1630116e-07, 1.5200686e-06, 3.1620297e-05,
        1.7160302e-09, 2.1342753e-06],
       [3.4061316e-06, 3.4276657e-09, 1.4070274e-06, 1.5491374e-08,
        9.9474585e-01, 8.1425657e-07, 6.4863893e-06, 9.4367373e-05,
        1.6615706e-07, 5.1474143e-03]], dtype=float32)>